------ This table contains information about which positions are possible for a player to play in a game
CREATE TABLE public.games_possible_position (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    position_name TEXT NOT NULL,
    is_titulaire BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT games_possible_position_pkey PRIMARY KEY (id),
    CONSTRAINT games_possible_position_position_name_key UNIQUE (position_name)
) TABLESPACE pg_default;

INSERT INTO public.games_possible_position (id, position_name, is_titulaire) VALUES
    (1, 'Goalkeeper', TRUE),
    (2, 'Left WingBack', TRUE),
    (4, 'Left CenterBack', TRUE),
    (95, 'Central CenterBack', TRUE),
    (5, 'Right CenterBack', TRUE),
    (3, 'Right WingBack', TRUE),
    (7, 'Left Winger', TRUE),
    (6, 'Left MidFielder', TRUE),
    (96, 'Central MidFielder', TRUE),
    (10, 'Right MidFielder', TRUE),
    (8, 'Right Winger', TRUE),
    (9, 'Left Striker', TRUE),
    (99, 'Central Striker', TRUE),
    (11, 'Right Striker', TRUE),

    (12, 'Sub WingBack', FALSE),
    (13, 'Sub CenterBack', FALSE),
    (14, 'Sub Winger', FALSE),
    (15, 'Sub MidFielder', FALSE),
    (16, 'Sub Striker', FALSE),
    (17, 'Sub Extra', FALSE);