CREATE OR REPLACE FUNCTION clamp(value DOUBLE PRECISION, min_value DOUBLE PRECISION, max_value DOUBLE PRECISION)
RETURNS DOUBLE PRECISION AS $$
BEGIN
    RETURN LEAST(max_value, GREATEST(min_value, value));
END;
$$ LANGUAGE plpgsql;
