import 'package:opengoalz/models/player/class/player.dart';

class PlayerWithPosition {
  final String name;
  final String type; // Keeper, Defense, Midfield, Attack
  final String notesSmallDefault;
  final String shirtNumberDefault;
  final String database;
  int? id;
  Player? player;

  PlayerWithPosition({
    required this.name,
    required this.type,
    required this.notesSmallDefault,
    required this.shirtNumberDefault,
    required this.database,
    required this.id,
    required this.player,
  });

  /// This is a list of default players that are used to create a new team composition.
  static List<PlayerWithPosition> defaultPlayers = [
    PlayerWithPosition(
      name: 'Goal Keeper',
      type: 'Keeper',
      notesSmallDefault: 'GK',
      shirtNumberDefault: '1',
      database: 'idgoalkeeper',
      id: null,
      player: null,
    ),
    PlayerWithPosition(
      name: 'Left Back Winger',
      type: 'Defense',
      notesSmallDefault: 'BW_L',
      shirtNumberDefault: '2',
      database: 'idleftbackwinger',
      id: null,
      player: null,
    ),
    PlayerWithPosition(
      name: 'Left Central Back',
      type: 'Defense',
      notesSmallDefault: 'CB_L',
      shirtNumberDefault: '4',
      database: 'idleftcentralback',
      id: null,
      player: null,
    ),
    PlayerWithPosition(
      name: 'Central Back',
      type: 'Defense',
      notesSmallDefault: 'CB_C',
      shirtNumberDefault: '95',
      database: 'idcentralback',
      id: null,
      player: null,
    ),
    PlayerWithPosition(
      name: 'Right Central Back',
      type: 'Defense',
      notesSmallDefault: 'CB_R',
      shirtNumberDefault: '5',
      database: 'idrightcentralback',
      id: null,
      player: null,
    ),
    PlayerWithPosition(
      name: 'Right Back Winger',
      type: 'Defense',
      notesSmallDefault: 'BW_R',
      shirtNumberDefault: '3',
      database: 'idrightbackwinger',
      id: null,
      player: null,
    ),
    PlayerWithPosition(
      name: 'Left Winger',
      type: 'Midfield',
      notesSmallDefault: 'WI_L',
      shirtNumberDefault: '7',
      database: 'idleftwinger',
      id: null,
      player: null,
    ),
    PlayerWithPosition(
      name: 'Left Midfielder',
      type: 'Midfield',
      notesSmallDefault: 'MD_L',
      shirtNumberDefault: '6',
      database: 'idleftmidfielder',
      id: null,
      player: null,
    ),
    PlayerWithPosition(
      name: 'Central Midfielder',
      type: 'Midfield',
      notesSmallDefault: 'MD_C',
      shirtNumberDefault: '96',
      database: 'idcentralmidfielder',
      id: null,
      player: null,
    ),
    PlayerWithPosition(
      name: 'Right Midfielder',
      type: 'Midfield',
      notesSmallDefault: 'MD_R',
      shirtNumberDefault: '10',
      database: 'idrightmidfielder',
      id: null,
      player: null,
    ),
    PlayerWithPosition(
      name: 'Right Winger',
      type: 'Midfield',
      notesSmallDefault: 'WI_R',
      shirtNumberDefault: '8',
      database: 'idrightwinger',
      id: null,
      player: null,
    ),
    PlayerWithPosition(
      name: 'Left Striker',
      type: 'Attack',
      notesSmallDefault: 'ST_L',
      shirtNumberDefault: '9',
      database: 'idleftstriker',
      id: null,
      player: null,
    ),
    PlayerWithPosition(
      name: 'Central Striker',
      type: 'Attack',
      notesSmallDefault: 'ST_C',
      shirtNumberDefault: '99',
      database: 'idcentralstriker',
      id: null,
      player: null,
    ),
    PlayerWithPosition(
      name: 'Right Striker',
      type: 'Attack',
      notesSmallDefault: 'ST_R',
      shirtNumberDefault: '11',
      database: 'idrightstriker',
      id: null,
      player: null,
    ),
    PlayerWithPosition(
      name: 'Sub 1',
      type: 'Sub',
      notesSmallDefault: 'Sub1',
      shirtNumberDefault: '12',
      database: 'idsub1',
      id: null,
      player: null,
    ),
    PlayerWithPosition(
      name: 'Sub 2',
      type: 'Sub',
      notesSmallDefault: 'Sub2',
      shirtNumberDefault: '13',
      database: 'idsub2',
      id: null,
      player: null,
    ),
    PlayerWithPosition(
      name: 'Sub 3',
      type: 'Sub',
      notesSmallDefault: 'Sub3',
      shirtNumberDefault: '14',
      database: 'idsub3',
      id: null,
      player: null,
    ),
    PlayerWithPosition(
      name: 'Sub 4',
      type: 'Sub',
      notesSmallDefault: 'Sub4',
      shirtNumberDefault: '15',
      database: 'idsub4',
      id: null,
      player: null,
    ),
    PlayerWithPosition(
      name: 'Sub 5',
      type: 'Sub',
      notesSmallDefault: 'Sub5',
      shirtNumberDefault: '16',
      database: 'idsub5',
      id: null,
      player: null,
    ),
    PlayerWithPosition(
      name: 'Sub 6',
      type: 'Sub',
      notesSmallDefault: 'Sub6',
      shirtNumberDefault: '17',
      database: 'idsub6',
      id: null,
      player: null,
    ),
    PlayerWithPosition(
      name: 'Sub 7',
      type: 'Sub',
      notesSmallDefault: 'Sub7',
      shirtNumberDefault: '18',
      database: 'idsub7',
      id: null,
      player: null,
    ),
  ];
}
