name: Build and Release Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: flutter-actions/setup-flutter@v2
        with:
          flutter-version: 'stable' # Use the latest stable Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows executable
        run: flutter build windows

      - name: List build directory contents
        run: dir build/windows/x64/runner/Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: build/windows/x64/runner/Release/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-executable
          path: build/windows/x64/runner/Release/

      - name: List build directory contents
        run: ls build/windows/x64/runner/Release

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: 0.0.${{ github.run_number }}
          release_name: Release 0.0.${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Set release upload URL
        run: echo "RELEASE_UPLOAD_URL=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_ENV

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ env.RELEASE_UPLOAD_URL }}
          asset_path: build/windows/x64/runner/Release/opengoalz.exe
          asset_name: opengoalz.exe
          asset_content_type: application/octet-stream